// import {axios} from 'axios';

// For some reason import statement does not work with jest, 
// and node does not work well with react-script test
// So the functions to be tested are copied from the corresponding js file 
// Tests that require external libraries are conducted manually 

const courseList = [
    "AERO ST",
    "AF AMER",
    "AFRC ST",
    "AM IND",
    "ANES",
    "ANTHRO",
    "AF LANG",
    "APPLING",
    "ARCHEOL",
    "ARCH&UD",
    "ART",
    "ART HIS",
    "ART&ARC",
    "ASIA AM",
    "ASIAN",
    "CHIN",
    "FILIPNO",
    "HIN-URD",
    "INDO",
    "JAPAN",
    "KOREA",
    "S ASIAN",
    "SEASIAN",
    "THAI",
    "VIETMSE",
    "A&O SCI",
    "BIOENGR",
    "BIOINFO",
    "BIOL CH",
    "BIOMATH",
    "BMD RES",
    "BIOSTAT",
    "CH ENGR",
    "APP CHEM",
    "CHEM",
    "CHICANO",
    "CCAS",
    "CIVIC",
    "C&EE",
    "CLASSIC",
    "GREEK",
    "LATIN",
    "CLUSTER",
    "COMM",
    "COMM ST",
    "CESC",
    "COM HLT",
    "COM LIT",
    "C&S BIO",
    "BIOMATH",
    "BIOINFR",
    "COM SCI",
    "CLT HTG",
    "DENT",
    "ORL BIO",
    "DESMA",
    "DGT HUM",
    "DIS STD",
    "EPS SCI",
    "EA STDS",
    "EE BIOL",
    "ECON",
    "EDUC",
    "EC ENGR",
    "EL ENGR",
    "ENGR",
    "ENGL",
    "ENVIRON",
    "ENV HLT",
    "EPIDEM",
    "ETHNOMU",
    "ETHNMUS",
    "DUTCH",
    "ELTS",
    "FRNCH",
    "GERMAN",
    "ITALIAN",
    "SCAND",
    "YIDDSH",
    "FAM MED",
    "FIAT LX",
    "FILM TV",
    "FOOD ST",
    "GENDER",
    "GE CLST",
    "GEOG",
    "GRNTLGY",
    "GLB HLT",
    "GJ STDS",
    "GLBL ST",
    "GRAD PD",
    "HLT POL",
    "HLT ADM",
    "HIST",
    "HNRS",
    "HUM GEN",
    "I E STD",
    "INF STD",
    "PHYSCI",
    "I A STD",
    "INTL DV",
    "I M STD",
    "LBR&WS",
    "LBR STD",
    "LATN AM",
    "LAW",
    "UG-LAW",
    "LGBTS",
    "LGBTQS",
    "LIFESCI",
    "ASL",
    "LING",
    "SWAHILI",
    "IEP",
    "MGMT",
    "MGMTEX",
    "MGMTFT",
    "MGMTFE",
    "MGMTGEX",
    "MGMTMFE",
    "MGMTMSA",
    "MGMTPHD",
    "MAT SCI",
    "MATH",
    "COMPTNG",
    "MECH&AE",
    "MED",
    "MIMG",
    "MIL SCI",
    "M PHARM",
    "MOL BIO",
    "MOL TOX",
    "MCD BIO",
    "MC&IP",
    "MIA STD",
    "MUSIC",
    "MUSC",
    "MUS IND",
    "MSC IND",
    "MUS HST",
    "MSC HST",
    "MUSCLGY",
    "MUSCLG",
    "NAV SCI",
    "AN N EA",
    "ARABIC",
    "ARMENIA",
    "HEBREW",
    "IRANIAN",
    "ISLM ST",
    "JEWISH",
    "M E STD",
    "NR EAST",
    "SEMITIC",
    "TURKIC",
    "MED HIS",
    "NEURBIO",
    "NEURLGY",
    "NEUROSC",
    "NEURO",
    "NEURSGY",
    "NONDEPT",
    "NURSING",
    "OBGYN",
    "OPTH",
    "ORTHPDC",
    "PATH",
    "PEDS",
    "PHILOS",
    "ASTR",
    "PHYSICS",
    "QNT SCI",
    "PBMED",
    "PHYSIOL",
    "POL SCI",
    "PSYCTRY",
    "PSYCH",
    "PUB AFF",
    "PUB HLT",
    "PUB PLC",
    "RAD ONC",
    "RELIGN",
    "RES PRC",
    "SCAND",
    "SCI EDU",
    "BULGR",
    "C&EE ST",
    "CZCH",
    "HNGAR",
    "LTHUAN",
    "POLSH",
    "ROMANIA",
    "RUSSN",
    "SRB CRO",
    "SLAVC",
    "UKRN",
    "SOC SC",
    "SOC THT",
    "SOC WLF",
    "SOC GEN",
    "SOCIOL",
    "IL AMER",
    "PORTGSE",
    "SPAN",
    "STATS",
    "SUMMER",
    "SURGERY",
    "THEATER",
    "UNIV ST",
    "URBN PL",
    "UROLOGY",
    "ARTS ED",
    "DANCE",
    "WL ARTS",
    "ESL",
    "ENGCOMP"
];

function validateCourse(course) {
    var c = null;
    for (c of courseList) {
        if (course.trim() === c) {
            //alert("true");
            return true;
        }
    }
    //alert("false");
    return false;
};

test('course validation test', () => {
    expect(validateCourse('COM SCI')).toEqual(true);
    expect(validateCourse('comsci')).toEqual(false);
    expect(validateCourse('CS')).toEqual(false);
    expect(validateCourse('         MATH           ')).toEqual(true);
    // validateCourse() expects the input argument has all capital letters, which is 
    // guaranteed by the caller function in the main module. 
    expect(validateCourse('com sci')).toEqual(false); 
});

// jest.mock('axios');
